### ISSUE TITLE
how to upgrade to spring boot 2.0?

### ISSUE THREAD

**Issue by JamesXiao** [QianmiOpen/spring-boot-starter-rocketmq#1]
Hi,

The demo works like a charm under spring boot 1.5.7.
But it meets some problems when I change the maven dependency to 2.0.0, the error message goes like:

> ***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'com.qianmi.ms.starter.rocketmq.core.RocketMQTemplate' that could not be found.
	- Bean method 'rocketMQTemplate' in 'RocketMQAutoConfiguration' not loaded because @ConditionalOnBean (types: org.apache.rocketmq.client.producer.DefaultMQProducer; SearchStrategy: all) did not find any beans of type org.apache.rocketmq.client.producer.DefaultMQProducer

Action:

Consider revisiting the conditions above or defining a bean of type 'com.qianmi.ms.starter.rocketmq.core.RocketMQTemplate' in your configuration.

Any hint on how to fix this?

**Comment by aqlu** [comment]
Maybe the same problem with https://github.com/apache/rocketmq-externals/pull/32#issuecomment-369209036

**Comment by JamesXiao** [comment]
Thank you , problem solved.
